### ISSUE TITLE
The package needs other package that not exists

### ISSUE THREAD

**Issue by IgorDePaula** [Setasign/SetaPDF-Signer-Addon-AWS-KMS#11]
setasign/setapdf-signer

![image](https://github.com/Setasign/SetaPDF-Signer-Addon-AWS-KMS/assets/2833993/ac4ff434-de43-4a83-ad6e-2113ceb419c5)

In packagist.org or in your github not have this repository

=/

**Comment by MaximilianKresse** [comment]
Yes this is correctly. This package is only available through our private repository on [setasign.com](https://www.setasign.com/). More Details about the SetaPDF-Signer can be found here: [https://www.setasign.com/products/setapdf-signer/details/](https://www.setasign.com/products/setapdf-signer/details/)

**Comment by IgorDePaula** [comment]
If the package does not download all dependence, it has a defect.

**Comment by MaximilianKresse** [comment]
I'm sorry but the SetaPDF-Signer is a commercial product. You'll need a license to be able to download it. 

But if you want to try it out you can request a trial license here: https://www.setasign.com/products/setapdf-signer/trial/
Please note: the trial license will require you to install the ioncube loader on your testing machine because the source code is encrypted.

If you have a license you can download the package with composer by adding the repository to your composer.json:
```json
    "repositories": [
        {
            "type": "composer",
            "url": "https://www.setasign.com/downloads/"
        }
    ]
```
